apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - command: helm install casskop orange-incubator/cassandra-operator --set image.tag=cassie4
    namespaced: true
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
spec:
  nodesPerRacks: 1
  cassandraImage: cassandra:4.0-rc1
  serverVersion: 4.0.0
  dataCapacity: "256Mi"
  hardAntiAffinity: false
  deletePVC: true
  autoPilot: true
  autoUpdateSeedList: false
  dataStorageClass: local-path
  backRestSidecar:
    resources:
      limits:
        memory: 128Mi
        cpu: 100m
  resources:
    limits:
      memory: 512Mi
      cpu: 200m
  topology:
    dc:
      - name: dc1
        rack:
          - name: rack1