apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - command: helm install casskop orange-incubator/cassandra-operator --set image.tag=1.0.2-restore-rename
    namespaced: true
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
spec:
  nodesPerRacks: 2
  cassandraImage: cassandra:3.11.9
  dataCapacity: "256Mi"
  hardAntiAffinity: false
  deletePVC: true
  autoPilot: true
  autoUpdateSeedList: false
  dataStorageClass: local-path
  backRestSidecar:
    image: gcr.io/cassandra-operator/instaclustr-icarus:1.0.8
    resources:
      requests: &backRestRequests
        memory: 512Mi
        cpu: 100m
      limits: *backRestRequests
  resources:
    requests: &requests
      memory: 512Mi
      cpu: 200m
    limits: *requests
  topology:
    dc:
      - name: dc1
        rack:
          - name: rack1
