apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - command: helm install casskop orange-incubator/cassandra-operator --set image.tag=cassie4
    namespaced: true
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
spec:
  nodesPerRacks: 2
  cassandraImage: cassandra:3.11.9
  bootstrapImage: orangeopensource/cassandra-bootstrap:0.1.8
  dataCapacity: "256Mi"
  hardAntiAffinity: false
  deletePVC: true
  autoPilot: true
  autoUpdateSeedList: false
  dataStorageClass: local-path
  backRestSidecar:
    image: gcr.io/cassandra-operator/instaclustr-icarus:1.1.0
    resources: &resources
      limits:
        memory: 512Mi
        cpu: 200m
  resources: *resources
  topology:
    dc:
      - name: dc1
        rack:
          - name: rack1
