---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  # Fill Cassandra tables
  - command: kubectl exec -ti cassandra-e2e-dc1-rack1-0 -- /opt/cassandra/tools/bin/cassandra-stress write n=2000 cl=one -rate threads=1 -mode native cql3 user=cassandra password=cassandra -col names=c1 -schema 'Keyspace=k1 replication(strategy=NetworkTopologyStrategy, dc1=2)'
  # Fill Cassandra tables
  - command: "kubectl exec -ti cassandra-e2e-dc1-rack1-0 -- cqlsh -k k1 \"CREATE TABLE standard2(key blob PRIMARY KEY, c1 blob) WITH compression = {'enabled': 'false'};\""
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraBackup
metadata:
  name: backup-compat-tests
spec:
  cassandraCluster: cassandra-e2e
  datacenter: dc1
  storageLocation: s3://casskop-backup-restore-test
  snapshotTag: CassOpCassKopCompatTest
  secret: aws-backup-secrets
  entities: k1.standard1