apiVersion: kuttl.dev/v1beta1
kind: TestSuite
# crdDir: ./operator/deploy/crds
testDirs:
  - .
commands:
 - command: helm repo add datastax https://datastax.github.io/charts --force-update
   ignoreFailure: true
 - command: helm delete cass-operator
   ignoreFailure: true
 - command: helm install cass-operator datastax/cass-operator --set defaultImage=cscetbon/cass-operator:master,clusterWideInstall=true
   ignoreFailure: true
timeout: 600
parallel: 1
