apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cluster1-scaling-rack1-sts
status:
  currentReplicas: 1
  readyReplicas: 1
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: scaling
spec:
  clusterName: cluster1
  size: 1
  racks:
    - name: rack1
status:
  cassandraOperatorProgress: Ready
