apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cluster1-scaling-rack1-sts
  namespace: cass-operator
status:
  currentReplicas: 2
  readyReplicas: 2
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: scaling
  namespace: cass-operator
spec:
  clusterName: cluster1
  size: 2
status:
  cassandraOperatorProgress: Ready
