apiVersion: db.orange.com/v1alpha1
kind: MultiCasskop
metadata:
  name: cassandra-e2e
  namespace: cluster1
spec:
  deleteCassandraCluster: true
  base:
    apiVersion: db.orange.com/v1alpha1
    kind: CassandraCluster
    metadata:
      name: cassandra-e2e
    spec:
      nodesPerRacks: 1
      cassandraImage: cassandra:3.11.9
    status:
      seedlist:
        - cassandra-e2e-dc1-rack1-0.cassandra-e2e.cluster1
  override:
    cluster:
      metadata:
        namespace: cluster1
      spec:
        topology:
          dc:
            - name: dc1
              rack: &rack
                - name: rack1
    k8s-cluster2:
      metadata:
        namespace: cluster2
      spec:
        topology:
          dc:
            - name: dc2
              rack: *rack
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-e2e-dc1-rack1
  namespace: cluster1
status:
  currentReplicas: 1
  replicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-e2e-dc2-rack1
  namespace: cluster2
status:
  currentReplicas: 1
  replicas: 1
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
  namespace: cluster1
status:
  lastClusterAction: Initializing
  lastClusterActionStatus: Done
  phase: Running
---
apiVersion: db.orange.com/v1alpha1
kind: CassandraCluster
metadata:
  name: cassandra-e2e
  namespace: cluster2
status:
  lastClusterAction: Initializing
  lastClusterActionStatus: Done
  phase: Running
