apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multidcs-dc1-rack1-sts
  namespace: n1
status:
  currentReplicas: 1
  readyReplicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multidcs-dc2-rack1-sts
  namespace: n2
status:
  currentReplicas: 1
  readyReplicas: 1
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
  namespace: n1
spec:
  clusterName: multidcs
  size: 1
  racks:
    - name: rack1
# Status can't be tested until https://github.com/datastax/cass-operator/issues/329 is fixed
# status:
#   cassandraOperatorProgress: Ready
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc2
  namespace: n2
spec:
  clusterName: multidcs
  size: 1
  racks:
    - name: rack1
# status:
#   cassandraOperatorProgress: Ready
