apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multidcs-dc1-rack1-sts
status:
  currentReplicas: 1
  readyReplicas: 1
---
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: multidcs
  size: 1
  racks:
    - name: rack1
status:
  cassandraOperatorProgress: Ready
